### ISSUE TITLE
BUG: after write command help, programm just exit

### ISSUE THREAD

**Issue by sea5kg** [LoinASD/console_client#16]
1. First session: login and qnother
2. Second session:
   alex@alex:~/develop/fhq_client.git$ ./console-client.py 
   All commands types conjoint or with hyphen.
   Usage: <command|two-words-command> [params]
   Type 'help' for commands list or 'help -r' for regular expressions list.
   /> help
   alex@alex:~/develop/fhq_client.git$

**Comment by sea5kg** [comment]
Привет а ты проверяешь после фиксов ?

**Comment by loinasd** [comment]
да. мне пришлось откатиться прост
